language: cpp
dist: trusty
sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc
      env: COMPILER=g++-5
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: g++-5

    - os: linux
      compiler: gcc
      env: COMPILER=g++-6
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: g++-6

    - os: linux
      compiler: gcc
      env:
        - COMPILER=g++-7
        - DOCS="true"
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-7

    - os: linux
      compiler: gcc
      env:
        - COMPILER=g++-8
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-8

    - os: linux
      compiler: gcc
      env:
        - COMPILER=g++-8
        - CXXFLAGS=-std=c++17
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-8

    - os: linux
      compiler: clang
      env: COMPILER=clang++-5.0
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-5.0']
          packages: ['clang-5.0', 'libstdc++-7-dev']

    - os: linux
      compiler: clang
      env: COMPILER=clang++-6.0
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-6.0']
          packages: ['clang-6.0', 'libstdc++-7-dev']

    - os: osx
      osx_image: xcode9

    - os: osx
      osx_image: xcode10


script:
  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi
  - uname -a
  - $CXX --version

  - mkdir -p build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build . -- VERBOSE=1 -j4
  - ctest -V
  - cd ..
